"""round_2_remediation

Revision ID: 179119f23cd3
Revises: 31872bec4dcf
Create Date: 2026-01-31 20:45:44.455323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179119f23cd3'
down_revision: Union[str, Sequence[str], None] = '31872bec4dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargas_excel', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('cargas_excel', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ninos', 'dni_madre',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ninos', 'nombre_madre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('ninos', 'celular_madre',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ninos', 'rango_edad',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ninos', 'historia_clinica',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ninos', 'establecimiento_asignado',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ninos', 'establecimiento_asignado',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('ninos', 'historia_clinica',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('ninos', 'rango_edad',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('ninos', 'celular_madre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('ninos', 'nombre_madre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('ninos', 'dni_madre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('cargas_excel', 'estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('cargas_excel', 'updated_at')
    # ### end Alembic commands ###
