"""Add status to CargaExcel

Revision ID: 31872bec4dcf
Revises: 3d0e28afc945
Create Date: 2026-01-28 20:12:08.122930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31872bec4dcf'
down_revision: Union[str, Sequence[str], None] = '3d0e28afc945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargas_excel', sa.Column('estado', sa.String(length=20), nullable=True))
    op.add_column('cargas_excel', sa.Column('mensaje_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargas_excel', 'mensaje_error')
    op.drop_column('cargas_excel', 'estado')
    # ### end Alembic commands ###
