"""Add indices and stabilize schema

Revision ID: 3d0e28afc945
Revises: 
Create Date: 2026-01-28 20:09:31.224071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0e28afc945'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_carga_user_periodo', 'cargas_excel', ['user_id', 'anio', 'mes'], unique=False)
    op.create_index(op.f('ix_cargas_excel_id'), 'cargas_excel', ['id'], unique=False)
    op.create_index(op.f('ix_cargas_excel_user_id'), 'cargas_excel', ['user_id'], unique=False)
    op.alter_column('ninos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ninos', 'direccion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_ninos_dni'), table_name='ninos')
    op.drop_constraint(op.f('ninos_dni_nino_key'), 'ninos', type_='unique')
    op.create_index('idx_nino_user_est', 'ninos', ['user_id', 'establecimiento_asignado'], unique=False)
    op.create_index(op.f('ix_ninos_dni_nino'), 'ninos', ['dni_nino'], unique=False)
    op.create_index(op.f('ix_ninos_id'), 'ninos', ['id'], unique=False)
    op.create_index(op.f('ix_ninos_user_id'), 'ninos', ['user_id'], unique=False)
    op.alter_column('usuario_config', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_usuario_config_id'), 'usuario_config', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_config_usuario'), 'usuario_config', ['usuario'], unique=True)
    op.alter_column('visitas', 'observacion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('visitas', 'fecha_visita',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index('idx_visita_user_fecha', 'visitas', ['user_id', 'fecha_visita'], unique=False)
    op.create_index(op.f('ix_visitas_actor_social'), 'visitas', ['actor_social'], unique=False)
    op.create_index(op.f('ix_visitas_establecimiento_atencion'), 'visitas', ['establecimiento_atencion'], unique=False)
    op.create_index(op.f('ix_visitas_estado'), 'visitas', ['estado'], unique=False)
    op.create_index(op.f('ix_visitas_fecha_visita'), 'visitas', ['fecha_visita'], unique=False)
    op.create_index(op.f('ix_visitas_id'), 'visitas', ['id'], unique=False)
    op.create_index(op.f('ix_visitas_nino_id'), 'visitas', ['nino_id'], unique=False)
    op.create_index(op.f('ix_visitas_user_id'), 'visitas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_user_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_nino_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_id'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_fecha_visita'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_estado'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_establecimiento_atencion'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_actor_social'), table_name='visitas')
    op.drop_index('idx_visita_user_fecha', table_name='visitas')
    op.alter_column('visitas', 'fecha_visita',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('visitas', 'observacion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_usuario_config_usuario'), table_name='usuario_config')
    op.drop_index(op.f('ix_usuario_config_id'), table_name='usuario_config')
    op.alter_column('usuario_config', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ninos_user_id'), table_name='ninos')
    op.drop_index(op.f('ix_ninos_id'), table_name='ninos')
    op.drop_index(op.f('ix_ninos_dni_nino'), table_name='ninos')
    op.drop_index('idx_nino_user_est', table_name='ninos')
    op.create_unique_constraint(op.f('ninos_dni_nino_key'), 'ninos', ['dni_nino'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ninos_dni'), 'ninos', ['dni_nino'], unique=False)
    op.alter_column('ninos', 'direccion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ninos', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_cargas_excel_user_id'), table_name='cargas_excel')
    op.drop_index(op.f('ix_cargas_excel_id'), table_name='cargas_excel')
    op.drop_index('idx_carga_user_periodo', table_name='cargas_excel')
    # ### end Alembic commands ###
